name: Scrape Articles and Create Markdown

on:
  schedule:
    - cron: '0 8,20 * * *' # Runs at 00:00 and 12:00 PST (Philippine Standard Time)
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  scrape-and-create:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Run the scraping and markdown creation process
      - name: Run scraping scripts
        run: |
          python scrape.py

      # Run the scraping and markdown creation process
      - name: Run MD generation scripts
        run: |
          python createMD.py

      # Removing __pycache__
      - name: Remove __pycache__
        run: |
          rm -rf '__pycache__'

      # Commit
      - name: Commit files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *
          git commit -m "UPDATE DATA: $(date +'%b. %d, %Y (%a) %I:%M:%S %p') UTC"
          git push